**Matrix** : A matrix is a rectangular table of numbers arranged in rows and columns.

In [47]:
import numpy as np

In [48]:
A = np.array([[1,2,3],[4,5,6]])

print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [49]:
zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [50]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.7372763  0.9278339  0.35897629]
 [0.78406797 0.75765817 0.18748042]
 [0.53307232 0.60066618 0.40997851]]


In [52]:
ones_matrix = np.ones((3,3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Transpose of a matrix** : The transpose of a matrix means rows become columns and columns become rows.
$$A^{T}$$

In [53]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print(A)

# transpose_matrix = A.T
transpose_matrix = np.transpose(A)
print(transpose_matrix)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [73]:
A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])

# C = A + B
C = np.add(A, B)

print("Matrix Addition:")
print(C)

Matrix Addition:
[[ 6  8]
 [10 12]]


In [74]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# D = A - B
D = np.subtract(A, B)

print("Matrix Subtraction:")
print(D)

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]


In [75]:
import numpy as np

A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])

# C = np.multiply(A, B)
C = A * B
print("Matrix Multiplication(elementwise):")
print(C)

Matrix Multiplication(elementwise):
[[ 5 12]
 [21 32]]


In [76]:
A = np.array([[1,2],[3,4]])
result = 3 * A

print("Scalar Multiplication:")
print(result)

Scalar Multiplication:
[[ 3  6]
 [ 9 12]]


In [77]:
import numpy as np

A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])

# C = np.matmul(A, B)
C = A @ B
print("Matrix Multiplication:")
print(C)

Matrix Multiplication:
[[19 22]
 [43 50]]


$$dodproduct = multiplication$$

In [78]:
import numpy as np

A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])

# C = np.matmul(A, B)
C = np.dot(A, B)
print("Dod product:")
print(C)

Dod product:
[[19 22]
 [43 50]]
